# Generated by Django 4.1.7 on 2023-02-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_fournisseur1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.fournisseur1'),
        ),
    ]
